description: "made this after drinking too much coffee"
email: "madelinekim14@g.ucla.edu"
twitter: "https://twitter.com/thecarpentries"

team_members:
  -
    name: "Iced Coffee"
    role: "yes ow"
    start_date: "2024-06-28"
  -
    name: "Matcha"
    role: notreally
    start_date: "2024-07-01"
  -
    name: "Tom Cat"
    role: rarely
    start_date: "2023-06-24"
  -
    name: "Alie Dauncey"
    role: "developer"
    start_date: "2020-09-15"
    
